- name: Elasticsearch with custom configuration
  hosts: test
  become: true
  become_user: root
  roles:
  gather_facts: False
  vars:
    apt_cache_valid_time: 86400
    # This can be overridden on the command line with --extra-vars "skip_install=true" for a faster run
    skip_install: false
  pre_tasks:
  - name: 'install python2'
    raw: sudo apt-get -y install python-simplejson
    when: not skip_install
  tasks:
  - name: include installation tasks
    include: tasks/install.yaml
    when: not skip_install

  - name: include configuration tasks
    include: tasks/configure.yaml
  
  - name: include services
    include: tasks/install.yaml
    when: not skip_install
