- name: Elasticsearch with custom configuration
  hosts: test
  become: true
  become_user: root
  roles:
  gather_facts: False
  vars:
    first_run: false
    apt_cache_valid_time: 86400
  pre_tasks:
  - name: 'install python2'
    raw: sudo apt-get -y install python-simplejson
    when: first_run
  tasks:
  - name: Update apt cache
    apt: update_cache=yes cache_valid_time={{ apt_cache_valid_time }}

  # Java
  - name: Add Oracle Java Repository
    apt_repository: repo='ppa:webupd8team/java' update_cache=yes codename=jessie
    when: first_run
  - name: Accept Java 8 License
    when: first_run
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  - name: Install Oracle Java 8
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    when: first_run

  # Add Elastic stack repositories
  - name: add Elastic key
    apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present
  - name: install necessary packages to get elastic stack
    apt: name={{item}} state=present
    with_items:
      - aptitude
      - apt-transport-https
  - name: install elasticsearch repository
    apt_repository: repo="deb https://artifacts.elastic.co/packages/5.x/apt stable main" state=present update_cache=yes


  # Install and configure Elasticsearch
  - name: install elasticsearch
    apt: name=elasticsearch state=present
    register: installed_elasticsearch
  - name: Enable elasticsearch service services
    service: name=elasticsearch enabled=yes
    when: installed_elasticsearch
  - name: Put elasticsearch configuration
    copy:
      src: files/etc/elasticsearch/{{item}}
      dest: /etc/elasticsearch/{{item}}
      owner: root
      group: elasticsearch
    with_items:
      - elasticsearch.yml
      - jvm.options
    register: configured_elasticsearch
  - name: Restart elasticsearch
    service: name=elasticsearch state=restarted
    when: configured_elasticsearch.changed or installed_elasticsearch.changed

  # Install and configure logstash
  - name: install logstash
    apt: name=logstash state=present
    register: installed_logstash
  - name: Enable logstash service services
    service: name=logstash enabled=yes
    when: installed_logstash
  - name: Put logstash configuration
    copy:
      src: files/etc/logstash/{{item}}
      dest: /etc/logstash/{{item}}
      owner: root
      group: root
    with_items:
      - logstash.yml
      - jvm.options
    register: configured_logstash
#  - debug: msg="configured_logstash={{configured_logstash}}"
#  - debug: msg="installed_logstash={{installed_logstash}}"
  - name: Restart logstash
    service: name=logstash state=restarted
    when: configured_logstash.changed or installed_logstash.changed


  # Install and configure kibana
  - name: install kibana
    apt: name=kibana state=present
    register: installed_kibana
  - name: Enable kibana service services
    service: name=kibana enabled=yes
    when: installed_kibana
  - name: Put kibana configuration
    copy:
      src: files/etc/kibana/{{item}}
      dest: /etc/kibana/{{item}}
      owner: root
      group: root
    with_items:
      - kibana.yml
    register: configured_kibana
  - name: Restart kibana
    service: name=kibana state=restarted
    when: configured_kibana.changed or installed_kibana.changed


