- name: Elasticsearch with custom configuration
  hosts: master-data-1
  become: true
  become_user: root
  roles:
  gather_facts: False
  vars:
    apt_cache_valid_time: 86400
    # This can be overridden on the command line with --extra-vars "skip_install=true" for a faster run
    skip_install: false
  pre_tasks:
  - name: 'install python2'
    apt: 
      name: "{{ item }}"
      state: present
    with_items:
      - ca-certificates
      - python-simplejson
      - rsync
      - curl # very useful for debugging
    when: not skip_install
  tasks:
  - name: include installation tasks
    include: tasks/install.yaml
    when: not skip_install

  - name: include configuration tasks
    include: tasks/configure.yaml
  
  - debug: msg="configured_logstash"
  - name: include services
    include: tasks/services.yaml
    when: not skip_install
