#------------------------------ Prospectors -----------------------------------
filebeat.prospectors:
- input_type: nginx
  paths:
    - /var/log/*.log
  fields:
    type: nginx
  fields_under_root: true

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["localhost:5044"]

