#------------------------------ Prospectors -----------------------------------
filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/boxes/*/access.log*
  exclude_files: ['\.gz$']
  fields:
    type: nginx-access
  fields_under_root: true

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["localhost:5044"]

